### ISSUE TITLE
插件加载出错，[Main] Cannot find module 'object-path'

### ISSUE THREAD

**Issue by Aqua99476** [xh321/LiteLoaderQQNT-Background-Plugin#66]
## 错误信息
```
[Main] Cannot find module 'object-path'
Require stack:
- E:\QQNT\resources\liteloader_num\plugins\background_plugin\main.js
- E:\QQNT\resources\app\LiteLoaderQQNT-main\src\main.js
- E:\QQNT\resources\app\LiteLoaderQQNT-main\src\init.js
- E:\QQNT\resources\app\app_launcher\index.js
- 
Error: Cannot find module 'object-path'
Require stack:
- E:\QQNT\resources\liteloader_num\plugins\background_plugin\main.js
- E:\QQNT\resources\app\LiteLoaderQQNT-main\src\main.js
- E:\QQNT\resources\app\LiteLoaderQQNT-main\src\init.js
- E:\QQNT\resources\app\app_launcher\index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:120699)
    at Module._load (node:internal/modules/cjs/loader:993:27)
    at f._load (node:electron/js2c/node_init:2:18640)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (E:\QQNT\resources\liteloader_num\plugins\background_plugin\main.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
```
## 插件信息
```
{"manifest":{"manifest_version":4,"type":"extension","name":"背景插件","slug":"background_plugin","description":"在QQNT聊天界面轮播展示背景图，同时让QQNT界面透明化以便更好地展示背景图。","version":"0.2.19","icon":"./icon.png","authors":[{"name":"XiaoHe321","link":"https://github.com/xh321"}],"repository":{"repo":"xh321/LiteLoaderQQNT-Background-Plugin","branch":"master","release":{"tag":"0.2.19","file":"Background.zip"}},"platform":["win32","darwin","linux"],"injects":{"renderer":"./renderer.js","main":"./main.js","preload":"./preload.js"}},"incompatible":false,"disabled":false,"path":{"plugin":"E:\\QQNT\\resources\\liteloader_num\\plugins\\background_plugin","data":"E:\\QQNT\\resources\\liteloader_num\\data\\background_plugin","injects":{"main":"E:\\QQNT\\resources\\liteloader_num\\plugins\\background_plugin\\main.js","preload":"E:\\QQNT\\resources\\liteloader_num\\plugins\\background_plugin\\preload.js","renderer":"E:\\QQNT\\resources\\liteloader_num\\plugins\\background_plugin\\renderer.js"}},"error":{"message":"[Main] Cannot find module 'object-path'\nRequire stack:\n- E:\\QQNT\\resources\\liteloader_num\\plugins\\background_plugin\\main.js\n- E:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\src\\main.js\n- E:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\src\\init.js\n- E:\\QQNT\\resources\\app\\app_launcher\\index.js\n- ","stack":"Error: Cannot find module 'object-path'\nRequire stack:\n- E:\\QQNT\\resources\\liteloader_num\\plugins\\background_plugin\\main.js\n- E:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\src\\main.js\n- E:\\QQNT\\resources\\app\\LiteLoaderQQNT-main\\src\\init.js\n- E:\\QQNT\\resources\\app\\app_launcher\\index.js\n- \n    at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)\n    at s._resolveFilename (node:electron/js2c/browser_init:2:120699)\n    at Module._load (node:internal/modules/cjs/loader:993:27)\n    at f._load (node:electron/js2c/node_init:2:18640)\n    at Module.require (node:internal/modules/cjs/loader:1240:19)\n    at require (node:internal/modules/helpers:179:18)\n    at Object.<anonymous> (E:\\QQNT\\resources\\liteloader_num\\plugins\\background_plugin\\main.js:5:18)\n    at Module._compile (node:internal/modules/cjs/loader:1373:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)\n    at Module.load (node:internal/modules/cjs/loader:1215:32)"}}
```
```
["anti_recall","background_plugin","deepl_plugin","DemoMode","fake_message","gpt_reply","image_search","list-viewer","lite_tools","media_local_view","MessageEdit","more_materials","mspring_theme","qr_code"]
```

## 环境信息
```
{"qqnt":"9.9.12-25765","liteloader":"1.1.2","node":"20.14.0","chrome":"126.0.6478.36","electron":"31.0.1","platform":"win32"}
```

未知，最开始安装时可用，禁用一次后再开出现此问题

**Comment by xh321** [comment]
有依赖包丢了，建议手动删除插件，然后从release重新下载完整zip再重新安装一次
