### ISSUE TITLE
[1.2.0]新版本liteloader有bug

### ISSUE THREAD

**Issue by yhzcake** [xh321/LiteLoaderQQNT-Background-Plugin#71]
错误信息:
```[Main] Cannot find module 'object-path'
Require stack:
- D:\LiteloaderQQNT\plugins\background_plugin\main.js
- D:\LiteloaderQQNT\src\loader_core\main.js
- D:\LiteloaderQQNT\src\main.js
- D:\LiteloaderQQNT\src\init.js
- D:\Program Files\Tencent\QQNT\resources\app\app_launcher\index.js
- 
Error: Cannot find module 'object-path'
Require stack:
- D:\LiteloaderQQNT\plugins\background_plugin\main.js
- D:\LiteloaderQQNT\src\loader_core\main.js
- D:\LiteloaderQQNT\src\main.js
- D:\LiteloaderQQNT\src\init.js
- D:\Program Files\Tencent\QQNT\resources\app\app_launcher\index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)
    at s._resolveFilename (node:electron/js2c/browser_init:2:120699)
    at Module._load (node:internal/modules/cjs/loader:993:27)
    at f._load (node:electron/js2c/node_init:2:18640)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (D:\LiteloaderQQNT\plugins\background_plugin\main.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
```
插件信息:
```
{"manifest":{"manifest_version":4,"type":"extension","name":"背景插件","slug":"background_plugin","description":"在QQNT聊天界面轮播展示背景图，同时让QQNT界面透明化以便更好地展示背景图。","version":"0.2.21","icon":"./icon.png","authors":[{"name":"XiaoHe321","link":"https://github.com/xh321"}],"repository":{"repo":"xh321/LiteLoaderQQNT-Background-Plugin","branch":"master","release":{"tag":"0.2.21","file":"Background.zip"}},"platform":["win32","darwin","linux"],"injects":{"renderer":"./renderer.js","main":"./main.js","preload":"./preload.js"}},"incompatible":false,"disabled":false,"path":{"plugin":"D:\\LiteloaderQQNT\\plugins\\background_plugin","data":"D:\\LiteloaderQQNT\\data\\background_plugin","injects":{"main":"D:\\LiteloaderQQNT\\plugins\\background_plugin\\main.js","preload":"D:\\LiteloaderQQNT\\plugins\\background_plugin\\preload.js","renderer":"D:\\LiteloaderQQNT\\plugins\\background_plugin\\renderer.js"}},"error":{"message":"[Main] Cannot find module 'object-path'\nRequire stack:\n- D:\\LiteloaderQQNT\\plugins\\background_plugin\\main.js\n- D:\\LiteloaderQQNT\\src\\loader_core\\main.js\n- D:\\LiteloaderQQNT\\src\\main.js\n- D:\\LiteloaderQQNT\\src\\init.js\n- D:\\Program Files\\Tencent\\QQNT\\resources\\app\\app_launcher\\index.js\n- ","stack":"Error: Cannot find module 'object-path'\nRequire stack:\n- D:\\LiteloaderQQNT\\plugins\\background_plugin\\main.js\n- D:\\LiteloaderQQNT\\src\\loader_core\\main.js\n- D:\\LiteloaderQQNT\\src\\main.js\n- D:\\LiteloaderQQNT\\src\\init.js\n- D:\\Program Files\\Tencent\\QQNT\\resources\\app\\app_launcher\\index.js\n- \n    at Module._resolveFilename (node:internal/modules/cjs/loader:1152:15)\n    at s._resolveFilename (node:electron/js2c/browser_init:2:120699)\n    at Module._load (node:internal/modules/cjs/loader:993:27)\n    at f._load (node:electron/js2c/node_init:2:18640)\n    at Module.require (node:internal/modules/cjs/loader:1240:19)\n    at require (node:internal/modules/helpers:179:18)\n    at Object.<anonymous> (D:\\LiteloaderQQNT\\plugins\\background_plugin\\main.js:5:18)\n    at Module._compile (node:internal/modules/cjs/loader:1373:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)\n    at Module.load (node:internal/modules/cjs/loader:1215:32)"}}
```
```
["background_plugin","brevity-btn","chii_devtools","deepl_plugin","DemoMode","directly_jump","kill-update","list-viewer","lite_tools","mspring_theme","qr_code","scriptio","text_to_speech","transitio","window_on_top"]
```

环境信息:
```
{"qqnt":"9.9.12-26466","liteloader":"1.2.0","node":"20.14.0","chrome":"126.0.6478.36","electron":"31.0.1","platform":"win32"}
```

**Comment by xh321** [comment]
请仔细阅读readme，你这是缺npm包，要么从release下载完整zip解压，要么手动npm i安装依赖
