### ISSUE TITLE
使用时背景视频突然不动了，重启之后无论如何重新安装都报错

### ISSUE THREAD

**Issue by ZXH2333** [xh321/LiteLoaderQQNT-Background-Plugin#77]
![image](https://github.com/user-attachments/assets/1520e869-dd3d-4e88-b215-483d1695f65d)
错误信息：
[Main] Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at loadConfig (D:\RevokeMsgPatcher.v1.9\RevokeMsgPatcher.v1.9\LiteLoaderQQNT\plugins\background_plugin\main.js:368:17)
    at Object.<anonymous> (D:\RevokeMsgPatcher.v1.9\RevokeMsgPatcher.v1.9\LiteLoaderQQNT\plugins\background_plugin\main.js:45:17)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at f._load (node:electron/js2c/node_init:2:18636)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)

插件信息：
{"manifest":{"manifest_version":4,"type":"extension","name":"背景插件","slug":"background_plugin","description":"在QQNT聊天界面轮播展示背景图，同时让QQNT界面透明化以便更好地展示背景图。","version":"0.2.21","icon":"./icon.png","authors":[{"name":"XiaoHe321","link":"https://github.com/xh321"}],"repository":{"repo":"xh321/LiteLoaderQQNT-Background-Plugin","branch":"master","release":{"tag":"0.2.21","file":"Background.zip"}},"platform":["win32","darwin","linux"],"injects":{"renderer":"./renderer.js","main":"./main.js","preload":"./preload.js"}},"incompatible":false,"disabled":false,"path":{"plugin":"D:\\RevokeMsgPatcher.v1.9\\RevokeMsgPatcher.v1.9\\LiteLoaderQQNT\\plugins\\background_plugin","data":"D:\\RevokeMsgPatcher.v1.9\\RevokeMsgPatcher.v1.9\\LiteLoaderQQNT\\data\\background_plugin","injects":{"main":"D:\\RevokeMsgPatcher.v1.9\\RevokeMsgPatcher.v1.9\\LiteLoaderQQNT\\plugins\\background_plugin\\main.js","preload":"D:\\RevokeMsgPatcher.v1.9\\RevokeMsgPatcher.v1.9\\LiteLoaderQQNT\\plugins\\background_plugin\\preload.js","renderer":"D:\\RevokeMsgPatcher.v1.9\\RevokeMsgPatcher.v1.9\\LiteLoaderQQNT\\plugins\\background_plugin\\renderer.js"}},"error":{"message":"[Main] Unexpected end of JSON input","stack":"SyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at loadConfig (D:\\RevokeMsgPatcher.v1.9\\RevokeMsgPatcher.v1.9\\LiteLoaderQQNT\\plugins\\background_plugin\\main.js:368:17)\n    at Object.<anonymous> (D:\\RevokeMsgPatcher.v1.9\\RevokeMsgPatcher.v1.9\\LiteLoaderQQNT\\plugins\\background_plugin\\main.js:45:17)\n    at Module._compile (node:internal/modules/cjs/loader:1373:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)\n    at Module.load (node:internal/modules/cjs/loader:1215:32)\n    at Module._load (node:internal/modules/cjs/loader:1031:12)\n    at f._load (node:electron/js2c/node_init:2:18636)\n    at Module.require (node:internal/modules/cjs/loader:1240:19)\n    at require (node:internal/modules/helpers:179:18)"}}

["background_plugin","DemoMode","euphony","fake_message","justf5","list-viewer","media_local_view","MessageEdit","anti_recall","qr_code","telegram_theme","window_on_top"]

环境信息：
{"qqnt":"9.9.15-28418","liteloader":"1.2.2","node":"20.14.0","chrome":"126.0.6478.36","electron":"31.0.2","platform":"win32"}

**Comment by xh321** [comment]
手动删一下配置文件吧，不知道怎么回事损坏了，在profile目录/data/background/config.json，这个profile目录默认就是plugins所在的那个目录
